import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Represents a log event generated by the Scheduler system.
 * This class encapsulates structured logging information including:
 * - timestamp of the event
 * - severity level
 * - component that generated the log
 * - thread identifier
 * - human-readable message
 *
 * This is typically used for formatted logging in the Scheduler log output.
 */
public class SchedulerEventClass {
    /** Timestamp when the event was created, formatted as HH:mm:ss.SSS */
    private final String timestamp;
    /** Severity level of the event (eg INFO, DEBUG, ERROR) */
    private final String level;
    /** Component that generated the event (eg Scheduler, DroneSubsystem) */
    private final String component;
    /** Tag for the thread or subsystem that logged the event (eg "SD", "SF", "MAIN") */
    private final String threadTag;
    /** Descriptive message belonging to the event */
    private final String message;

    /**
     * creates a SchedulerEventClass instance with the specified log metadata:
     *
     * @param level     the severity level of the event (e.g., INFO, ERROR)
     * @param component the component generating the log
     * @param threadTag identifier for the thread or subsystem
     * @param message   a description of the event
     */
    public SchedulerEventClass(String level, String component, String threadTag, String message) {
        this.timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss.SSS"));
        this.level = level;
        this.component = component;
        this.threadTag = threadTag;
        this.message = message;
    }

    /**
     * @return the formatted log string [timestamp] [level] [component] [threadTag] message
     */
    @Override
    public String toString() {
        return String.format("[%s] [%s] [%s] [%s] %s", timestamp, level, component, threadTag, message);
    }
}